# -*- coding: utf-8 -*-
"""Case Study Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aU0c_5lsKc1SGA56jlCH34-7hIah7qCI
"""

# Student Grade Calculator
Marks = [20,30,50,35,20]
average=sum(Marks)/len(Marks)

if(average>=90):
    print(f"The average of student is {average} and the Grade is A")
elif(average>=70 and average<80):
    print((f"The average of student is {average} and the Grade is B"))
elif(average>=50 and average<70):
    print((f"The average of student is {average} and the Grade is C"))
else:
    print(f"The average of student is {average} and the Grade is F and student is failed")

# Automate ticket booking for customers.
availseats = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

while True:

    try:
        Bkdseat = int(input("Please select your seat number (1-20) or enter 0 to exit: "))


        if Bkdseat == 0:
            print("Thank you for using the seat booking system. Goodbye!")
            break

        if Bkdseat in availseats:
            availseats.remove(Bkdseat)
            print(f"Your seat {Bkdseat} has been booked successfully.")
            print(f"Remaining available seats: {availseats}")
        else:
            print("Sorry, this seat has already been booked or is invalid.")

    except ValueError:
        print("Please enter a valid number for the seat.")

# Application to calculate the total bill for a customer in a grocery store
item_prices = {'apple': 50,'orange': 40,'biscuit': 20,'rice': 30,'wheat': 25}

total_bill = 0

print("Available items and the price of items:")

for item, price in item_prices.items():
    print(f"{item.capitalize()}: {price} per unit")

while True:
    item = input("Please Enter the item you want to buy (or type 'done' to finish): ").lower()

    if item == 'done':
        break

    if item in item_prices:
        try:
            quantity = int(input(f"Enter the quantity of {item}: "))

            total_bill += item_prices[item] * quantity
            print(f"Added {quantity} {item}(s) to the bill.")
        except ValueError:
            print("Please enter a valid quantity.")
    else:
        print("Sorry, we don't have that item. Please choose from the available items.")

print(f"\nYour total bill is: {total_bill} units.")